// List of programmer jokes
const jokes = [
    "Why do programmers prefer dark mode? Because light attracts bugs!",
    "There are only 10 kinds of people in this world: those who understand binary and those who don’t.",
    "How many programmers does it take to change a light bulb? None. That's a hardware problem!",
    "A programmer's favorite place to hang out? The Foo bar.",
    "Why do Java developers wear glasses? Because they don't C#!",
    "What is a programmer’s favorite snack? Microchips.",
    "Why did the programmer quit his job? Because he didn’t get arrays.",
    "Why do programmers hate nature? Because it has too many bugs.",
    "Why did the software developer go broke? Because he used up all his cache!",
    "How do you comfort a JavaScript bug? You console it.",
    "Why was the developer unhappy at their job? They wanted arrays.",
    "Why don’t programmers like to use the elevator? Because they prefer to take steps.",
    "Why was the function sad after a breakup? It lost its closure.",
    "What do you call a programmer from Finland? Nerdic.",
    "Why did the programmer cross the road? To fix a bug on the other side.",
    "What's a programmer's favorite type of music? Algo-rhythm.",
    "Why did the programmer go broke? He lost his domain in a bidding war.",
    "What’s a programmer’s favorite hangout spot? Stack Overflow.",
    "How does a computer get drunk? It takes screenshots.",
    "Why was the computer cold? It left its Windows open.",
    "What do you call 8 hobbits? A hobbyte.",
    "Why did the PowerPoint presentation cross the road? To get to the next slide.",
    "Why was the computer tired when it got home? It had a hard drive.",
    "What do you call an iPhone that isn’t kidding around? Dead Siri-ous.",
    "Why did the computer sneeze? It had a virus!",
    "Why are assembly programmers always wet? They work below C-level.",
    "What’s a programmer’s favorite place to eat? Byte-sized portions.",
    "Why do programmers love coffee? Because it helps them debug.",
    "Why was the developer late for work? He had cache issues.",
    "Why did the programmer bring a ladder to work? To reach new heights in development.",
    "What do you call a lazy computer programmer? A pragma-tist.",
    "Why do programmers prefer keyboards over mice? Because they need more control.",
    "Why was the software engineer so calm? He always stayed in a try-catch block.",
    "What’s a programmer’s favorite kind of chips? Computer chips.",
    "Why did the programmer refuse to go outside? There were too many bugs.",
    "Why did the array break up? It found someone else to join.",
    "What’s a programmer’s favorite sport? Ping Pong.",
    "Why do programmers prefer using the terminal? Because it’s their command center.",
    "Why was the developer so good at cooking? He always followed the recipe to the letter.",
    "Why did the computer keep freezing? It left its Windows open.",
    "What do you call a computer floating in the ocean? A Dell Rolling in the Deep.",
    "Why did the programmer get stuck in traffic? He forgot to use recursion.",
    "Why don’t programmers like nature? It has too many branches.",
    "Why did the variable break up with the constant? It needed some space.",
    "Why do programmers love sushi? Because it’s byte-sized.",
    "What do you call a group of 8 bits? A byte club.",
    "Why was the programmer bad at relationships? He had too many unresolved dependencies.",
    "Why did the programmer go broke? He couldn’t find his root directory.",
    "Why did the coder fail his test? He couldn’t find his syntax.",
    "Why did the database administrator break up with his girlfriend? She had too many connections.",
    "How do you comfort a bug? You console it.",
    "Why did the programmer take a nap? He needed to clear his cache.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
    "Why did the developer go to therapy? He had too many unresolved promises.",
    "Why do programmers love cats? Because they always land on their feet, just like a try block.",
    "Why did the programmer’s wife leave him? He kept objectifying her.",
    "Why did the programmer throw his clock out the window? He wanted to see time fly.",
    "Why was the computer hot? It needed to cool its cores.",
    "What do you call a programmer who can't stop talking? A loop.",
    "Why was the math book sad? It had too many algorithms.",
    "Why did the CSS developer go broke? He couldn’t justify his expenses.",
    "What do you get when you cross a computer and a life coach? A debugger.",
    "Why did the programmer rewrite his code? He didn’t like the way it looked.",
    "What’s a programmer’s favorite fruit? A Raspberry Pi.",
    "Why did the programmer always carry a screwdriver? To debug his hardware.",
    "Why don’t programmers get lost? They always have a pointer.",
    "Why was the developer bad at hide and seek? He kept getting caught in infinite loops.",
    "Why did the programmer take up gardening? He loved working with branches.",
    "Why do programmers always carry a pencil? In case they need to draw a diagram.",
    "Why do programmers hate camping? Too many cache misses.",
    "Why did the programmer name his dog ‘Java’? Because it barked in code.",
    "Why do programmers prefer glasses? They improve their vision.",
    "Why did the programmer quit his diet? He couldn’t handle the cookies.",
    "Why do programmers never get bored? They always find a loop to entertain themselves.",
    "Why couldn’t the programmer finish his novel? He couldn’t find the right syntax.",
    "Why do programmers love sandwiches? Because they come with layers.",
    "Why do programmers love the ocean? It’s full of C.",
    "Why did the programmer delete his calendar? He didn’t have enough time for it.",
    "Why was the debugger so good at his job? He could spot a bug from a mile away.",
    "Why do programmers hate birds? They keep tweeting.",
    "Why did the programmer go to the beach? To work on his tan-gent.",
    "What do programmers and superheroes have in common? They both debug!"
];

// Display a random joke in the footer
const jokeElement = document.getElementById("programmer-joke");
if (jokeElement) {
    const randomJoke = jokes[Math.floor(Math.random() * jokes.length)];
    jokeElement.textContent = randomJoke;
}